added error handling

diff --git a/.github/workflows/CITests.yml b/.github/workflows/CITests.yml
--- a/.github/workflows/CITests.yml
+++ b/.github/workflows/CITests.yml
@@ -25,4 +25,16 @@ jobs:
       
       - name: Run Unit Tests
         run: |
-          python -m unittest discover -s tests
+          set +e
+          pytest -s -v .
+          EXIT_CODE=$?
+          set -e
+          if [ $EXIT_CODE -eq 5 ]; then
+            echo "No tests found"
+            exit 0
+          elif [ $EXIT_CODE -eq 0 ]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
